### ISSUE TITLE
Generate mouse move and click

### ISSUE THREAD

**Issue by jgilbert2017** [ToCSharp/AsyncChromeDriver#1]
First off, GREAT job on this project!  It looks awesome.

I was wondering if you could help me with some sample code.

I would like to click an image on a web page.

Ideally there would be some mouse movement to the image location and then a mouse click event on the image that exactly emulates a user doing the same.

Thanks!

**Comment by ToCSharp** [comment]
Thank you for kind words.  
I created new project with [AsyncChromeDriverExamplesAndTests ](https://github.com/ToCSharp/AsyncChromeDriverExamplesAndTests). 
There are examples of mouse and clicks usage. 
And there was ISSUE with clicks IN 0.1.5 VERSION. Update AsyncChromeDriver to 0.1.6 (VerifyElementClickable fix)

**Comment by jgilbert2017** [comment]
Fantastic, works like a charm!

Another question-

I've been looking through the sources and it seems like quite a lot is done via script injection/evaluation.

Can you tell me where the code in atom.cs came from in case I want to tweak it or add my own higher level functions?

For example, I have a very long text string I want to set an input element to so I think I would need to add something similar to the code in `ElementCommands.GetElementLocation` but the minified js code is kind of mystifying me :-)!

Thanks!!!

**Comment by ToCSharp** [comment]
https://github.com/SeleniumHQ/selenium/tree/master/javascript is base.  
https://cs.chromium.org/chromium/src/chrome/test/chromedriver/js/ 
https://cs.chromium.org/chromium/src/chrome/test/chromedriver/README.txt
more info tomorrow

**Comment by ToCSharp** [comment]
> For example, I have a very long text string I want to set an input element to (SendKeys is too slow)  

You do not need to send keys one by one. Send whole string  
`await query.SendKeys("ToCSharp");`

**Comment by ToCSharp** [comment]
Code in atom.cs came from https://cs.chromium.org/chromium/src/third_party/webdriver/atoms.cc?dr=CSs
