### ISSUE TITLE
Package Install Error

### ISSUE THREAD

**Issue by waliarubal** [ToCSharp/AsyncChromeDriver#12]
I am trying to install the latest package from NuGet, its failing with below error.

NU1102: Unable to find package Zu.ChromeDevToolsClient with version (>= 0.5.6)
  - Found 2 version(s) in nuget.org [ Nearest version: 0.5.5 ]
  - Found 0 version(s) in Microsoft Visual Studio Offline Packages
Package restore failed. Rolling back package changes for 'JustDialScraper.Ui'.

**Comment by ToCSharp** [comment]
Thank you. Fixed
