### ISSUE TITLE
Example project missing files

### ISSUE THREAD

**Issue by stekyne** [ToCSharp/AsyncChromeDriver#2]
Hi, thanks for this project, looks great.

There are some files missing from the example project. The BaristaLabs assembly, the Log\ClearCommand.cs and the rest of the files that should be there are not in the repo.

[Failure] Could not find file 'C:\dev\libraries\AsyncChromeDriver\BaristaLabs.chrome-dev-tools-runtime\BaristaLabs.ChromeDevTools.Runtime.NetFramework\Log\ClearCommand.cs'.
[Failure] Could not find file 'C:\dev\libraries\AsyncChromeDriver\BaristaLabs.chrome-dev-tools-runtime\BaristaLabs.ChromeDevTools.Runtime.NetFramework\Log\LogEntry.cs'.
[Failure] Could not find file 'C:\dev\libraries\AsyncChromeDriver\BaristaLabs.chrome-dev-tools-runtime\BaristaLabs.ChromeDevTools.Runtime.NetFramework\Log\ViolationSetting.cs'.
[Failure] Could not find file 'C:\dev\libraries\AsyncChromeDriver\BaristaLabs.chrome-dev-tools-runtime\BaristaLabs.ChromeDevTools.Runtime.NetFramework\Log\StopViolationsReportCommand.cs'.
[Failure] Could not find file 'C:\dev\libraries\AsyncChromeDriver\BaristaLabs.chrome-dev-tools-runtime\BaristaLabs.ChromeDevTools.Runtime.NetFramework\Log\EntryAddedEvent.cs'.
[Failure] Could not find file 'C:\dev\libraries\AsyncChromeDriver\BaristaLabs.chrome-dev-tools-runtime\BaristaLabs.ChromeDevTools.Runtime.NetFramework\Log\LogAdapter.cs'.
[Failure] Could not find file 'C:\dev\libraries\AsyncChromeDriver\BaristaLabs.chrome-dev-tools-runtime\BaristaLabs.ChromeDevTools.Runtime.NetFramework\Log\EnableCommand.cs'.
[Failure] Could not find file 'C:\dev\libraries\AsyncChromeDriver\BaristaLabs.chrome-dev-tools-runtime\BaristaLabs.ChromeDevTools.Runtime.NetFramework\Log\StartViolationsReportCommand.cs'.
[Failure] Could not find file 'C:\dev\libraries\AsyncChromeDriver\BaristaLabs.chrome-dev-tools-runtime\BaristaLabs.ChromeDevTools.Runtime.NetFramework\Log\DisableCommand.cs'.

**Comment by ToCSharp** [comment]
Thank you. 
It is new chrome-dev-tools-runtime feature. I forgot to add it to source control. I fix it. Please try.
And example must reference NuGet AsyncChromeDriver, but I left reference for tests. If you get errors, it's better change reference to Nuget.

**Comment by ToCSharp** [comment]
I do not reference to BaristaLabs Nuget because I have some changes in code and do not want use .Net Core for a while. Now only .Net framework

**Comment by stekyne** [comment]
Thanks
