### ISSUE TITLE
'Value cannot be null. Parameter name: endpointAddress' - when running VS 2017 in "Admin" mode

### ISSUE THREAD

**Issue by vamsitp** [ToCSharp/AsyncChromeDriver#3]
Possibly at [#L68](https://github.com/ToCSharp/AsyncChromeDriver/blob/00acce96b84ee27b079478a2ca87e4a8fae5dc47/BaristaLabs.chrome-dev-tools-runtime/BaristaLabs.ChromeDevTools.Runtime.NetFramework/ChromeSession.cs#L68) in ChromeSession.cs

**Comment by ToCSharp** [comment]
I have no such exception in "Admin" mode. You probably updated NuGet WebSocket4Net. Now only WebSocket4Net 0.14.1 supported
