### ISSUE TITLE
Which .net framework?

### ISSUE THREAD

**Issue by garfelddd** [ToCSharp/AsyncChromeDriver#4]
`Error		Could not install package 'AsyncChromeDriver 0.4.4'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.6', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.			0	
`
I've got error. Which version of .net do you recommend to use with the library?

**Comment by ToCSharp** [comment]
>= .NETFramework,Version=v4.6.2
